"""Adult scenarios for OmniVoice voice-cloning text generation."""

from typing import Dict, List

# Map scenario emotion keys to OmniVoice child-module emotion names (same tag set).
SCENARIO_EMOTION_MAP: Dict[str, str] = {
    "excited": "excited",
    "happy": "happy",
    "amused": "happy",
    "enthusiastic": "excited",
    "determined": "proud",
    "proud": "proud",
    "content": "happy",
    "affectionate": "happy",
    "relieved": "happy",
    "thoughtful": "confused",
    "curious": "curious",
    "confused": "confused",
    "surprised": "surprised",
    "shocked": "shocked",
    "angry": "angry",
    "frustrated": "frustrated",
    "sad": "sad",
    "disappointed": "disappointed",
    "tired": "tired",
    "anxious": "nervous",
    "professional": "happy",
    "playful": "playful",
    "sarcastic": "mischievous",
}

EMOTIONS: List[str] = sorted(set(SCENARIO_EMOTION_MAP.keys()))

SCENARIOS: Dict[str, dict] = {
    "daily_chat": {
        "name": "日常对话",
        "description": "朋友、家人、同事之间的自然口语",
        "subscenes": [
            "日常寒暄问候",
            "分享生活趣事",
            "吐槽抱怨琐事",
            "询问帮忙求助",
            "闲聊天气季节",
            "讨论美食吃饭",
            "交流兴趣爱好",
            "约会聊天",
            "家庭日常对话",
            "朋友聚会聊天",
            "邻里偶遇交谈",
        ],
        "typical_emotions": {
            "happy": 2.0,
            "amused": 1.8,
            "content": 1.5,
            "curious": 1.0,
            "frustrated": 0.8,
            "surprised": 0.6,
        },
    },
    "business": {
        "name": "商务/职场",
        "description": "会议、汇报、客户沟通、面试等专业场景",
        "subscenes": [
            "会议开场发言",
            "产品功能介绍",
            "客户沟通谈判",
            "工作进度汇报",
            "面试回答问题",
            "项目讨论协作",
            "演讲致辞",
            "商务谈判",
            "团队激励动员",
            "邮件口述回复",
            "技术方案讲解",
        ],
        "typical_emotions": {
            "determined": 2.0,
            "proud": 1.5,
            "professional": 1.5,
            "enthusiastic": 1.2,
            "thoughtful": 1.0,
            "relieved": 0.6,
        },
    },
    "education": {
        "name": "教育/讲解",
        "description": "课程讲解、知识科普、培训分享",
        "subscenes": [
            "课程知识讲解",
            "科学原理科普",
            "读书笔记分享",
            "语言学习方法",
            "技能操作指导",
            "历史故事讲述",
            "答疑解惑",
            "学习经验分享",
            "考试辅导",
            "成人在线课程",
        ],
        "typical_emotions": {
            "enthusiastic": 2.0,
            "thoughtful": 1.5,
            "curious": 1.2,
            "content": 1.0,
            "surprised": 0.6,
            "determined": 0.5,
        },
    },
    "emotional": {
        "name": "情感表达",
        "description": "告白、安慰、道歉、思念等情感场景",
        "subscenes": [
            "深情告白表白",
            "温暖安慰鼓励",
            "真诚道歉认错",
            "思念远方的人",
            "离别不舍告别",
            "感恩感谢表达",
            "委屈抱怨不满",
            "孤独失落倾诉",
            "后悔遗憾自责",
            "感动落泪瞬间",
        ],
        "typical_emotions": {
            "affectionate": 2.5,
            "sad": 1.5,
            "disappointed": 1.2,
            "relieved": 1.0,
            "anxious": 0.8,
            "angry": 0.6,
        },
    },
    "entertainment": {
        "name": "娱乐/创意",
        "description": "游戏解说、脱口秀、搞笑吐槽、角色演绎",
        "subscenes": [
            "游戏实况解说",
            "脱口秀段子",
            "搞笑短剧",
            "模仿配音",
            "综艺旁白",
            "搞笑吐槽",
            "影视reaction",
            "直播互动",
        ],
        "typical_emotions": {
            "enthusiastic": 2.5,
            "amused": 2.5,
            "surprised": 1.5,
            "excited": 1.5,
            "playful": 1.2,
            "sarcastic": 0.8,
        },
    },
    "narration": {
        "name": "叙述/旁白",
        "description": "纪录片、新闻、有声书、宣传片旁白",
        "subscenes": [
            "纪录片旁白解说",
            "企业宣传片配音",
            "旅游景点介绍",
            "新闻资讯播报",
            "有声书籍朗读",
            "品牌故事讲述",
            "展览导览解说",
            "电影解说旁白",
        ],
        "typical_emotions": {
            "content": 2.0,
            "thoughtful": 1.5,
            "surprised": 1.0,
            "enthusiastic": 0.8,
            "professional": 0.8,
        },
    },
    "social_media": {
        "name": "社交媒体",
        "description": "vlog、直播、探店、测评等新媒体口语",
        "subscenes": [
            "vlog日常生活",
            "开箱测评体验",
            "穿搭美妆分享",
            "美食探店吃播",
            "直播带货推荐",
            "观点分享评论",
            "旅行vlog记录",
            "健身运动打卡",
            "数码产品评测",
        ],
        "typical_emotions": {
            "enthusiastic": 2.5,
            "excited": 2.0,
            "amused": 1.5,
            "surprised": 1.2,
            "proud": 0.8,
            "playful": 0.8,
        },
    },
    "service": {
        "name": "客服/服务",
        "description": "电话客服、语音导航、预约提醒",
        "subscenes": [
            "电话客服应答",
            "在线客服回复",
            "语音导航提示",
            "自动通知播报",
            "预约确认提醒",
            "账单说明解释",
            "售后问题处理",
            "投诉建议回应",
        ],
        "typical_emotions": {
            "professional": 2.5,
            "content": 1.5,
            "relieved": 1.0,
            "affectionate": 0.8,
            "disappointed": 0.5,
        },
    },
    "creative_writing": {
        "name": "创意写作/文学",
        "description": "诗歌、散文、小说片段等文学朗读",
        "subscenes": [
            "现代散文朗读",
            "小说片段演绎",
            "戏剧对白朗读",
            "歌词深情演绎",
            "书信朗读",
            "微小说创作",
            "文学赏析评论",
            "经典名篇朗读",
        ],
        "typical_emotions": {
            "thoughtful": 2.0,
            "sad": 1.5,
            "affectionate": 1.2,
            "content": 1.0,
            "surprised": 0.8,
        },
    },
    "asr_stress": {
        "name": "ASR压力测试",
        "description": "数字串、快速朗读、情绪切换等极限场景",
        "subscenes": [
            "极快速朗读",
            "极慢速朗读",
            "情绪剧烈切换",
            "超长句连续朗读",
            "极短句片段",
            "中英混合切换",
            "数字串朗读",
            "口语化连读",
        ],
        "typical_emotions": {
            "excited": 1.5,
            "angry": 1.2,
            "surprised": 1.5,
            "anxious": 1.0,
            "enthusiastic": 1.0,
        },
        "is_stress_test": True,
    },
}

LENGTH_SPECS = {
    "ultra_short": {
        "cn": "极短，5-15个汉字，或3-10个英文单词。像随口一说的反应",
        "en": "Ultra short, 3-10 words. Like a quick reaction",
    },
    "short": {
        "cn": "短句，15-40个汉字/10-25个英文单词。一句完整口语",
        "en": "Short, 10-25 words. One complete spoken sentence",
    },
    "medium": {
        "cn": "中等，40-100个汉字/25-60个英文单词。可含一个小转折",
        "en": "Medium, 25-60 words. Can include a small twist",
    },
    "long": {
        "cn": "较长，100-250个汉字/60-150个英文单词。连续表达一小段",
        "en": "Long, 60-150 words. A short continuous passage",
    },
    "very_long": {
        "cn": "长句，250-500个汉字/150-300个英文单词。适合旁白或讲述",
        "en": "Very long, 150-300 words. Suitable for narration",
    },
}

LENGTH_BOUNDS = {
    "ultra_short": (5, 15),
    "short": (15, 40),
    "medium": (40, 100),
    "long": (100, 250),
    "very_long": (250, 500),
}

LANG_SPECS = {
    "pure_cn": "纯中文，不要出现任何英文字母",
    "pure_en": "Pure English, no Chinese characters",
    "cn_mostly": "以中文为主（80%+），自然混入1-3个常见英文词（OK、deadline、meeting等）",
    "en_mostly": "Mostly English (80%+), naturally mix in 1-3 common Chinese words",
    "frequent_mix": "自然的中英 code-switching，像双语职场/生活口语，句子中间切换",
}

LANG_MIX_SPECS = LANG_SPECS
